import type { Product, Seller, Store } from "./types";

/**
 * In-memory sample data for the frontend prototype.
 * This will be replaced by the Express + MongoDB API in the next phase —
 * the shapes match `lib/types.ts` so the swap is a drop-in.
 */

const img = (seed: string) => `https://picsum.photos/seed/${seed}/800/800`;
const cover = (seed: string) => `https://picsum.photos/seed/${seed}/1600/500`;

export const SELLERS: Seller[] = [
  {
    id: "sel_1",
    name: "Ayesha Khan",
    phone: "0300-1234567",
    email: "ayesha@example.com",
    status: "active",
    planId: "basic",
    subscriptionStatus: "active",
    storeId: "store_1",
    createdAt: "2026-01-12",
  },
  {
    id: "sel_2",
    name: "Bilal Ahmed",
    phone: "0321-9876543",
    email: "bilal@example.com",
    status: "active",
    planId: "growth",
    subscriptionStatus: "active",
    storeId: "store_2",
    createdAt: "2026-02-03",
  },
  {
    id: "sel_3",
    name: "Sana Malik",
    phone: "0333-5552211",
    email: "sana@example.com",
    status: "suspended",
    planId: "starter",
    subscriptionStatus: "suspended",
    storeId: "store_3",
    createdAt: "2026-03-21",
  },
];

export const STORES: Store[] = [
  {
    id: "store_1",
    sellerId: "sel_1",
    name: "Ayesha Boutique",
    slug: "ayesha-boutique",
    logoUrl: img("ayesha-logo"),
    coverUrl: cover("ayesha-cover"),
    description:
      "Hand-picked unstitched & ready-to-wear women's clothing. New arrivals every week.",
    category: "Clothing",
    whatsapp: "0300-1234567",
    city: "Lahore",
    area: "Gulberg",
    fullAddress: "Main Boulevard, Gulberg III, Lahore",
    mapsLink: "https://maps.google.com/?q=Gulberg+Lahore",
    showLocation: true,
    showInSearch: true,
    socials: { instagram: "ayesha.boutique", facebook: "ayeshaboutique" },
    deliveryInfo: "Delivery across Pakistan within 3-5 days.",
    paymentInfo: "Cash on Delivery / Bank transfer",
    status: "active",
    views: 420,
    whatsappClicks: 38,
  },
  {
    id: "store_2",
    sellerId: "sel_2",
    name: "Bilal Electronics",
    slug: "bilal-electronics",
    logoUrl: img("bilal-logo"),
    coverUrl: cover("bilal-cover"),
    description: "Genuine mobile accessories, smart gadgets and home electronics.",
    category: "Electronics",
    whatsapp: "0321-9876543",
    city: "Karachi",
    area: "Saddar",
    showLocation: true,
    showInSearch: true,
    socials: { instagram: "bilal.electronics" },
    deliveryInfo: "Same-day delivery within Karachi.",
    paymentInfo: "COD / EasyPaisa / JazzCash",
    status: "active",
    views: 980,
    whatsappClicks: 112,
  },
  {
    id: "store_3",
    sellerId: "sel_3",
    name: "Sana Cosmetics",
    slug: "sana-cosmetics",
    logoUrl: img("sana-logo"),
    coverUrl: cover("sana-cover"),
    description: "Affordable makeup and skincare essentials for everyday glam.",
    category: "Cosmetics",
    whatsapp: "0333-5552211",
    city: "Islamabad",
    showLocation: false,
    showInSearch: true,
    deliveryInfo: "Delivery in twin cities.",
    paymentInfo: "COD only",
    status: "active",
    views: 150,
    whatsappClicks: 9,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod_1",
    storeId: "store_1",
    name: "Black Embroidered Kurti",
    category: "Clothing",
    price: 2500,
    discountPrice: 1999,
    images: [img("kurti-1"), img("kurti-2"), img("kurti-3")],
    description: "Premium lawn kurti with detailed front embroidery. Sizes S-XL.",
    tags: ["kurti", "embroidered", "lawn", "women"],
    stockStatus: "in_stock",
    status: "active",
    negotiable: true,
    condition: "new",
    deliveryAvailable: true,
    moderationStatus: "approved",
    views: 210,
    whatsappClicks: 24,
    createdAt: "2026-04-01",
  },
  {
    id: "prod_2",
    storeId: "store_1",
    name: "Printed Summer Lawn 3-Piece",
    category: "Clothing",
    price: 4500,
    images: [img("lawn-1"), img("lawn-2")],
    description: "Unstitched 3-piece printed lawn suit with chiffon dupatta.",
    tags: ["lawn", "3-piece", "summer", "unstitched"],
    stockStatus: "in_stock",
    status: "active",
    negotiable: false,
    condition: "new",
    deliveryAvailable: true,
    moderationStatus: "approved",
    views: 96,
    whatsappClicks: 7,
    createdAt: "2026-04-10",
  },
  {
    id: "prod_3",
    storeId: "store_1",
    name: "Hand-Stitched Party Frock",
    category: "Clothing",
    price: 7800,
    images: [img("frock-1")],
    description: "Festive party wear frock with sequins.",
    tags: ["frock", "party", "festive"],
    stockStatus: "out_of_stock",
    status: "active",
    negotiable: true,
    condition: "new",
    moderationStatus: "pending",
    views: 40,
    whatsappClicks: 2,
    createdAt: "2026-05-02",
  },
  {
    id: "prod_4",
    storeId: "store_2",
    name: "Wireless Earbuds Pro",
    category: "Electronics",
    price: 3200,
    discountPrice: 2799,
    images: [img("earbuds-1"), img("earbuds-2")],
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    description: "Bluetooth 5.3 earbuds with noise cancellation and 24h battery.",
    tags: ["earbuds", "bluetooth", "audio", "wireless"],
    stockStatus: "in_stock",
    status: "active",
    negotiable: false,
    condition: "new",
    deliveryAvailable: true,
    moderationStatus: "approved",
    views: 530,
    whatsappClicks: 61,
    createdAt: "2026-03-15",
  },
  {
    id: "prod_5",
    storeId: "store_2",
    name: "Fast Charge 65W Adapter",
    category: "Electronics",
    price: 1800,
    images: [img("charger-1")],
    description: "GaN 65W USB-C charger compatible with laptops and phones.",
    tags: ["charger", "usb-c", "fast-charge"],
    stockStatus: "in_stock",
    status: "active",
    negotiable: true,
    condition: "new",
    deliveryAvailable: true,
    moderationStatus: "approved",
    views: 310,
    whatsappClicks: 28,
    createdAt: "2026-04-22",
  },
  {
    id: "prod_6",
    storeId: "store_2",
    name: "Smart Watch Series 9 (Clone)",
    category: "Electronics",
    price: 4999,
    images: [img("watch-1"), img("watch-2")],
    description: "Fitness tracking smartwatch with calling support.",
    tags: ["smartwatch", "fitness", "wearable"],
    stockStatus: "in_stock",
    status: "inactive",
    negotiable: true,
    condition: "new",
    moderationStatus: "flagged",
    views: 88,
    whatsappClicks: 5,
    createdAt: "2026-05-12",
  },
  {
    id: "prod_7",
    storeId: "store_3",
    name: "Matte Liquid Lipstick Set",
    category: "Cosmetics",
    price: 1500,
    discountPrice: 1199,
    images: [img("lipstick-1")],
    description: "Set of 6 long-lasting matte liquid lipsticks.",
    tags: ["lipstick", "matte", "makeup", "set"],
    stockStatus: "in_stock",
    status: "active",
    negotiable: false,
    condition: "new",
    deliveryAvailable: true,
    moderationStatus: "approved",
    views: 120,
    whatsappClicks: 14,
    createdAt: "2026-05-01",
  },
  {
    id: "prod_8",
    storeId: "store_3",
    name: "Vitamin C Brightening Serum",
    category: "Cosmetics",
    price: 2200,
    images: [img("serum-1")],
    description: "Brightening face serum with 10% vitamin C.",
    tags: ["serum", "skincare", "vitamin-c"],
    stockStatus: "in_stock",
    status: "active",
    negotiable: false,
    condition: "new",
    moderationStatus: "needs_edit",
    views: 33,
    whatsappClicks: 1,
    createdAt: "2026-05-18",
  },
];

/** The seller currently "logged in" for the dashboard prototype. */
export const CURRENT_SELLER_ID = "sel_1";
